import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "surface-container": "#eeeeee",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed-variant": "#5d4201",
        "primary-fixed-dim": "#c9c6c5",
        "primary-fixed": "#e5e2e1",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#211a13",
        "surface": "#f9f9f9",
        "on-primary-fixed": "#1c1b1b",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#4e453c",
        "secondary-container": "#fed488",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#5f5e5e",
        "primary": "#000000",
        "secondary-fixed-dim": "#e9c176",
        "on-primary-fixed-variant": "#474646",
        "inverse-primary": "#c9c6c5",
        "background": "#f9f9f9",
        "secondary": "#775a19",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadada",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#261900",
        "outline-variant": "#c4c7c7",
        "on-tertiary-container": "#8d8277",
        "secondary-fixed": "#ffdea5",
        "tertiary-fixed-dim": "#d1c4b8",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "on-background": "#1a1c1c",
        "outline": "#747878",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "tertiary-container": "#211a13",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed": "#eee0d3",
        "surface-variant": "#e2e2e2",
        "on-secondary-container": "#785a1a",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "section-gap": "120px",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-xl": ["Playfair Display", "serif"],
        serif: ["Playfair Display", "serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
